<?php
class ErrorCode
{
	const USERNAME_EXISTS = 1;
	const PASSWORD_CANNOT_EMPTY = 2;
	const USERNAME_CANNOT_EMPTY = 3;
	const REGISTER_FAIL = 4;
	const USERNAME_OR_PASSWORD_INVALID = 5;
	const ARTICLE_TITLE_CANNOT_EMPTY = 6;
	const ARTICLE_CONTENT_CANNOT_EMPTY = 7;
	const ARTICLE_CREATE_FAIL = 8;
	const ARTICLE_ID_CANNOT_EMPTY = 9;
	const ARTICLE_NOT_FOUND = 10;
	const PERMISSION_DENIED = 11;
	const ARTICLE_EDIT_FAIL = 12;
	const ARTICLE_DELETE_FAIL = 13;
	const PAGE_SIZE_TO_BIG = 14;
	const SERVER_INTERNAL_ERROR = 15;
}
?>